"use client"

import React from "react"
import { Button } from "@/components/ui/button"
import { Mic, Brain, BarChart3 } from "lucide-react"
import Link from "next/link"
import { useAuth } from "@/app/provider"

const Home = () => {
  const { user } = useAuth()

  return (
    <div className="min-h-screen bg-gray-50">

      {/* NAVBAR */}
      <nav className="w-full border-b bg-white sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 md:px-6 py-4 flex items-center justify-between">

          {/* Logo */}
          <Link href="/">
            <h2 className="text-xl font-bold text-blue-600">
              VoiceSaathi
            </h2>
          </Link>

          {/* Right Buttons */}
          <div className="flex items-center gap-2 md:gap-3">
            {user ? (
              <Link href="/dashboard">
                <Button variant="ghost" size="sm" className="md:text-base">Dashboard</Button>
              </Link>
            ) : (
              <Link href="/auth">
                <Button variant="ghost" size="sm" className="md:text-base">Login</Button>
              </Link>
            )}

            <Link href="/schedule-interview">
              <Button size="sm" className="md:text-base">Start Interview</Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* HERO SECTION */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-20 text-center">
        <h1 className="text-3xl md:text-5xl font-bold text-gray-900 leading-tight">
          Practice Interviews with
          <span className="text-blue-600"> VoiceSaathi</span>
        </h1>

        <p className="mt-4 md:mt-6 text-gray-600 text-base md:text-lg max-w-2xl mx-auto px-2">
          Prepare for real technical and behavioral interviews using our
          AI-powered mock interview platform. Get instant feedback,
          performance analysis, and improve your interview skills.
        </p>

        <div className="mt-8 flex flex-col sm:flex-row justify-center gap-4 px-6 sm:px-0">
          <Link href="/schedule-interview" className="w-full sm:w-auto">
            <Button size="lg" className="w-full">Start Mock Interview</Button>
          </Link>

          <Link href={user ? "/dashboard" : "/auth"} className="w-full sm:w-auto">
            <Button variant="outline" size="lg" className="w-full">
              {user ? "View Dashboard" : "Get Started"}
            </Button>
          </Link>
        </div>
      </section>

      {/* FEATURES */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 pb-20">
        <h2 className="text-2xl md:text-3xl font-semibold text-center mb-10 md:mb-12">
          Why Use Our Platform
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8">

          <div className="bg-white p-6 rounded-lg border text-center shadow-sm">
            <div className="flex justify-center mb-4">
              <Mic className="text-blue-600" size={32} />
            </div>
            <h3 className="font-semibold text-lg">AI Mock Interviews</h3>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              Practice real interview questions generated by AI for your
              target job role.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg border text-center shadow-sm">
            <div className="flex justify-center mb-4">
              <Brain className="text-blue-600" size={32} />
            </div>
            <h3 className="font-semibold text-lg">Smart Feedback</h3>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              Receive AI-powered evaluation on communication,
              technical skills, and problem solving.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg border text-center shadow-sm">
            <div className="flex justify-center mb-4">
              <BarChart3 className="text-blue-600" size={32} />
            </div>
            <h3 className="font-semibold text-lg">Performance Analytics</h3>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              Track your progress and identify areas to improve before
              real job interviews.
            </p>
          </div>

        </div>
      </section>

      {/* CTA SECTION */}
      <section className="bg-blue-600 py-12 md:py-16 text-center text-white px-4">
        <h2 className="text-2xl md:text-3xl font-semibold">
          Ready to Ace Your Next Interview?
        </h2>

        <p className="mt-3 text-blue-100 text-sm md:text-base">
          Start practicing today and boost your confidence.
        </p>

        <div className="mt-8">
          <Link href="/schedule-interview">
            <Button variant="secondary" size="lg" className="w-full sm:w-auto">
              Start Interview
            </Button>
          </Link>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="text-center py-8 text-gray-500 text-xs md:text-sm border-t">
        © {new Date().getFullYear()} VoiceSaathi • Built for Success
      </footer>

    </div>
  )
}

export default Home