"use client"

import React from "react"
import { Button } from "@/components/ui/button"
import { Mic, Brain, BarChart3 } from "lucide-react"
import Link from "next/link"

const Home = () => {
  return (
    <div className="min-h-screen bg-gray-50">

      {/* NAVBAR */}
      <nav className="w-full border-b bg-white">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">

          {/* Logo */}
          <Link href="/">
            <h2 className="text-xl font-bold text-blue-600">
              VoiceSaathi
            </h2>
          </Link>

          {/* Right Buttons */}
          <div className="flex items-center gap-3">
            <Link href="/dashboard">
              <Button variant="ghost">Dashboard</Button>
            </Link>

            <Link href="/schedule-interview">
              <Button>Start Interview</Button>
            </Link>
          </div>

        </div>
      </nav>

      {/* HERO SECTION */}
      <section className="max-w-6xl mx-auto px-6 py-20 text-center">
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 leading-tight">
          Practice Interviews with
          <span className="text-blue-600"> VoiceSaathi</span>
        </h1>

        <p className="mt-6 text-gray-600 text-lg max-w-2xl mx-auto">
          Prepare for real technical and behavioral interviews using our
          AI-powered mock interview platform. Get instant feedback,
          performance analysis, and improve your interview skills.
        </p>

        <div className="mt-8 flex justify-center gap-4">
          <Link href="/schedule-interview">
            <Button size="lg">Start Mock Interview</Button>
          </Link>

          <Link href="/dashboard">
            <Button variant="outline" size="lg">
              View Dashboard
            </Button>
          </Link>
        </div>
      </section>

      {/* FEATURES */}
      <section className="max-w-6xl mx-auto px-6 pb-20">
        <h2 className="text-3xl font-semibold text-center mb-12">
          Why Use Our Platform
        </h2>

        <div className="grid md:grid-cols-3 gap-8">

          <div className="bg-white p-6 rounded-lg border text-center">
            <div className="flex justify-center mb-4">
              <Mic className="text-blue-600" size={32} />
            </div>
            <h3 className="font-semibold text-lg">AI Mock Interviews</h3>
            <p className="text-gray-600 mt-2 text-sm">
              Practice real interview questions generated by AI for your
              target job role.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg border text-center">
            <div className="flex justify-center mb-4">
              <Brain className="text-blue-600" size={32} />
            </div>
            <h3 className="font-semibold text-lg">Smart Feedback</h3>
            <p className="text-gray-600 mt-2 text-sm">
              Receive AI-powered evaluation on communication,
              technical skills, and problem solving.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg border text-center">
            <div className="flex justify-center mb-4">
              <BarChart3 className="text-blue-600" size={32} />
            </div>
            <h3 className="font-semibold text-lg">Performance Analytics</h3>
            <p className="text-gray-600 mt-2 text-sm">
              Track your progress and identify areas to improve before
              real job interviews.
            </p>
          </div>

        </div>
      </section>

      {/* CTA SECTION */}
      <section className="bg-blue-600 py-16 text-center text-white">
        <h2 className="text-3xl font-semibold">
          Ready to Ace Your Next Interview?
        </h2>

        <p className="mt-3 text-blue-100">
          Start practicing today and boost your confidence.
        </p>

        <div className="mt-6">
          <Link href="/schedule-interview">
            <Button variant="secondary" size="lg">
              Start Interview
            </Button>
          </Link>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="text-center py-6 text-gray-500 text-sm">
        © {new Date().getFullYear()} VoiceSaathi
      </footer>

    </div>
  )
}

export default Home